version: '3.3'
services:
  filecoinDevelopment:
    build:
      context: .
      args:
        GOPROXY: 'http://192.168.1.201:70'
        GO111MODULE: 'on'
    image: lixianfadocker/filecoin
    container_name: filecoin
    volumes:
      - ./lotus:${HOMEDIR}/lotus:rw
      - ./go-filecoin:${HOMEDIR}/go-filecoin:rw
      - ./other:${HOMEDIR}/other:rw
      - ./.cargo:${HOMEDIR}/.cargo:rw
      - ./.rustup:${HOMEDIR}/.rustup:rw
      - /var/tmp/filecoin-parents:/var/tmp/filecoin-parents:rw
      - /var/tmp/filecoin-proof-parameters:/var/tmp/filecoin-proof-parameters:rw
    stdin_open: true
    tty: true
    command: tail -f /dev/null
